import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      smileDesigning: 'Smile Designing',
      alignersBraces: 'Aligners & Braces',
      dentalImplants: 'Dental Implants',
      aiPreview: 'AI Preview',
      results: 'Results',
      assessment: 'Assessment',
      faq: 'FAQ',
      contact: 'Contact',
      signIn: 'Sign In',
      register: 'Register',
      bookAppointment: 'Book Appointment',
      bookNow: 'Book Now',
      logout: 'Logout',
      welcome: 'Welcome'
    },
    home: {
      heroTitle: 'Where Perfect Smiles Are Crafted',
      heroSubtitle: 'Advanced dentistry for patients worldwide. Precision technology, accredited expertise, and genuine compassion.',
      bookConsultation: 'Book Free Consultation',
      viewServices: 'View Our Services',
      excellence: 'International Centre of Excellence',
      smiles: 'Smiles',
      crafted: 'Are Crafted',
      wherePerfect: 'Where Perfect',
      happyPatients: 'Happy Patients',
      countries: 'Countries',
      excellenceYrs: 'Excellence',
      rating: 'Rating',
      trust: {
        jci: 'JCI Accredited',
        jciD: 'Facility',
        iso: 'ISO 9001:2015',
        isoD: 'Certified',
        docs: '15+',
        docsD: 'Specialist Doctors',
        patients: '40+ Countries',
        patientsD: 'International Patients',
        emergency: 'Same‑Day',
        emergencyD: 'Emergency Care'
      },
      aboutTitle: 'About SmileVista',
      aboutH2: 'More than a clinic — a global smile centre',
      aboutP: 'Founded by internationally trained specialists, SmileVista combines cutting‑edge technology with genuine warmth. We treat local families and international travelers with the same high‑touch care, from consultation to aftercare.',
      aboutF1Title: '3D Digital Planning',
      aboutF1Desc: 'Preview your smile with CBCT + digital design workflow.',
      aboutF2Title: 'International Concierge',
      aboutF2Desc: 'Travel, hotel, airport pickup — coordinated end‑to‑end.',
      aboutF3Title: 'Lifetime Aftercare',
      aboutF3Desc: 'Remote check‑ins and support after you return home.',
      aboutF4Title: 'Anxiety‑Friendly Care',
      aboutF4Desc: 'Gentle approach with modern comfort options.',
      scheduleVisit: 'Schedule a Visit',
      takeQuiz: 'Take Smile Quiz',
      signatureTreatments: 'Signature Treatments',
      perfectSmile: 'Perfect Smile',
      discoverMore: 'Discover More',
      service1Desc: 'Digital planning for anatomical perfection and facial harmony.',
      service2Desc: 'Discreet orthodontic solutions for a lifetime of confidence.',
      service3Desc: 'Bio-compatible restorations that feel and function like natural teeth.',
      doctors: {
        title: 'Meet the Team',
        subtitle: 'World‑trained {specialists}',
        specialists: 'specialists',
        desc: 'Our clinicians hold advanced fellowships and deliver results with a balance of clinical precision and aesthetic artistry.',
        trained: 'Trained internationally',
        founder: 'Founder & Chief Dental Surgeon',
        oralMax: 'Oral & Maxillofacial',
        leadCosmetic: 'Lead Cosmetic & Aesthetic Dentist',
        cosmeticAesthetic: 'Cosmetic & Aesthetic',
        seniorImplant: 'Senior Implantologist',
        implantology: 'Implantology'
      },
      tourism: {
        title: 'Medical Tourism',
        subtitle: 'Your journey to a {better} smile',
        better: 'better',
        desc: 'Save 40–70% on world‑class dentistry. Our team helps with travel guidance, accommodation partners, and aftercare so you can focus on your treatment.',
        step1Title: 'Free virtual consultation',
        step1Desc: 'Share X‑rays/photos. Receive a plan and estimate within 24 hours.',
        step2Title: 'Travel & accommodation',
        step2Desc: 'Airport pickup + partner hotels minutes from the clinic.',
        step3Title: 'Treatment at SmileVista',
        step3Desc: 'Most multi‑procedure packages completed in 5–10 days.',
        step4Title: 'Lifetime remote aftercare',
        step4Desc: 'Digital records and follow‑ups after you return home.',
        btn: 'Plan My Dental Trip',
        whyTitle: 'Why India for dentistry?',
        whyDesc: 'World‑class outcomes at a fraction of the cost — with doctors trained in leading global institutions.',
        feat1Title: 'Direct flights',
        feat1Desc: 'From UAE, UK, US, AU + more',
        feat2Title: 'Hotel partners',
        feat2Desc: '4★ & 5★ at exclusive rates',
        feat3Title: 'Specialist team',
        feat3Desc: 'Cosmetic, implants, aligners',
        feat4Title: 'Visa support',
        feat4Desc: 'Documents + medical letter',
        savings: 'Average cost savings',
        vsCare: 'vs. equivalent care in UK, USA, or Australia'
      },
      testimonials: {
        title: 'Patient stories',
        subtitle: 'Smiles shared {across}',
        across: 'across the globe',
        desc: 'Real patients, real results — from London to Lagos, Sydney to São Paulo. Every smile tells a story of trust.',
        t1: '“I flew from Dubai for a full mouth reconstruction. From the first WhatsApp consult to the final fitting, everything was seamless. Worth every hour of travel.”',
        t2: '“I dreaded dentists, but here I felt completely at ease. Outstanding quality and value compared to UK prices.”',
        t3: '“My veneers are perfect. I consulted in three countries — the quality here exceeded all of them at a third of the price.”',
        experiencesTitle: 'Patient Experiences',
        exp1: 'Got my implants done — feels just like natural teeth.',
        exp2: 'Professional care and smooth experience from start to finish.',
        exp3: 'Completely changed my confidence and quality of life.'
      },
      contact: {
        title: 'Get in touch',
        subtitle: 'Book your {free} consultation',
        free: 'free consultation',
        desc: 'Whether local or international, our team creates your personalized plan. First consultations are free and include a complete digital assessment.',
        phone: 'Mon–Sat, 9 AM – 8 PM IST',
        email: 'Response within 2 hours',
        location: '15 mins from the city center',
        locName: 'Koramangala, Bengaluru, India',
        formTitle: 'Request an appointment',
        formSub: 'Fill out this quick form and we\'ll reach out to schedule your free consultation.',
        firstName: 'First name',
        lastName: 'Last name',
        emailLabel: 'Email',
        messageLabel: 'Message',
        messagePlaceholder: 'Tell us what you want to improve...',
        btnSend: 'Send Message',
        btnSending: 'Sending...',
        sentTitle: 'Message Sent!',
        sentSub: 'Thank you for reaching out. We\'ll get back to you shortly.',
        btnWhatsapp: 'Follow up on WhatsApp',
        btnAnother: 'Send another message',
        btnBooking: 'Go to Full Booking Page'
      }
    },
    services: {
      whyChoose: 'Why Choose This Treatment?',
      journeyTitle: 'Your Journey to a Perfect Smile',
      journeySub: 'A step-by-step clinical approach',
      theResult: 'The Result',
      resultSub: 'A masterpiece of aesthetic precision and clinical excellence',
      beforeTreatment: 'Before Treatment',
      afterReveal: 'After Reveal',
      transformation: 'Patient Transformation',
      quote: '"My confidence has never been higher. The precision is world-class."',
      readyTitle: 'Ready to Transform Your Smile?',
      readySub: 'Schedule your zero-cost consultation today and get a personalized 3D treatment plan.',
      bookNowBtn: 'Book Appointment Now',
      viewResultsBtn: 'View More Results'
    },
    smileDesigning: {
      title: "Digital Smile Designing",
      subtitle: "Precision-engineered smile makeovers tailored to your facial features and personality.",
      benefit1Title: "Aesthetic Harmony",
      benefit1Desc: "We align your teeth according to the 'Golden Ratio' for perfect facial symmetry.",
      benefit2Title: "3D Visualisation",
      benefit2Desc: "See your future smile on-screen before we even touch your teeth.",
      benefit3Title: "Single Day Procedure",
      benefit3Desc: "Many of our smile design cases are completed in just one or two sessions.",
      step1Title: "Digital Scan",
      step1Desc: "We take high-res digital impressions with our intraoral scanner.",
      step2Title: "Artistic Mapping",
      step2Desc: "Our specialists design your smile curve on professional dental software.",
      step3Title: "Trial Design",
      step3Desc: "You try a temporary mockup to ensure you love the look and feel.",
      step4Title: "Final Reveal",
      step4Desc: "Premium E-max veneers or bonding are applied for your final look."
    },
    alignersBraces: {
      title: "Aligners & Braces",
      subtitle: "The modern path to a straighter, healthier smile — discreetly and comfortably.",
      benefit1Title: "Invisible Comfort",
      benefit1Desc: "Clear aligners are virtually unnoticeable and can be removed for eating and cleaning.",
      benefit2Title: "Precision Moving",
      benefit2Desc: "3D treatment planning ensures each tooth moves exactly where it needs to be.",
      benefit3Title: "Healthier Gums",
      benefit3Desc: "Straight teeth are easier to clean, leading to better long-term oral health.",
      step1Title: "Consultation",
      step1Desc: "We assess your bite and discuss your alignment goals.",
      step2Title: "Digital Planning",
      step2Desc: "A digital 3D model shows your transformation from start to finish.",
      step3Title: "Custom Trays",
      step3Desc: "You receive a series of custom aligners to wear throughout your treatment.",
      step4Title: "Retention",
      step4Desc: "We provide retainers to keep your smile perfectly aligned for years."
    },
    dentalImplants: {
      title: "Dental Implants",
      subtitle: "Bio-compatible restorations that feel, look, and function exactly like natural teeth.",
      benefit1Title: "Natural Feel",
      benefit1Desc: "Implants fuse with your jawbone, providing unmatched stability and comfort.",
      benefit2Title: "Bone Health",
      benefit2Desc: "Prevents jawbone loss that typically follows tooth loss, preserving facial structure.",
      benefit3Title: "Lifelong Solution",
      benefit3Desc: "With proper care, dental implants are designed to last a lifetime.",
      step1Title: "Site Prep",
      step1Desc: "We ensure the foundation is healthy and ready for the implant.",
      step2Title: "Placement",
      step2Desc: "The titanium post is precisely placed into the jawbone.",
      step3Title: "Healing",
      step3Desc: "A period of osseointegration allows the implant to bond with the bone.",
      step4Title: "Restoration",
      step4Desc: "A custom crown is attached, completing your functional and aesthetic smile."
    },
    aiPreview: {
      title: 'AI Smile Preview',
      subtitle: 'Upload a photo and see your future smile in seconds using our advanced AI technology.',
      uploadTitle: 'Upload Your Photo',
      uploadSub: 'Ensure your teeth are visible for the best results',
      btnUpload: 'Choose Photo',
      btnProcess: 'Generate Preview',
      disclaimer: '*This is an AI-generated simulation for visualization purposes only.'
    },
    results: {
      title: 'Success Stories',
      subtitle: 'Real transformations from our global patients. Witness the power of precision dentistry.',
      filterAll: 'All Cases',
      filterSmile: 'Smile Design',
      filterAligners: 'Aligners',
      filterImplants: 'Implants'
    },
    assessment: {
      title: 'Smile Assessment',
      quizTitle: 'Smile Assessment Quiz',
      subtitle: 'Answer a few quick questions to get personalized recommendations',
      resultTitle: 'Your Treatment Plan',
      resultSub: 'Based on your answers, here\'s what we recommend',
      recTitle: 'Recommended Treatment',
      estCost: 'Estimated Cost',
      duration: 'Treatment Duration',
      successRate: 'Success Rate',
      nextSteps: 'What happens next?',
      step1: 'Schedule your free consultation',
      step2: 'Advanced 3D digital imaging',
      step3: 'Detailed treatment plan & pricing',
      step4: 'Flexible payment options available',
      retakeBtn: 'Retake Quiz',
      bookConsultBtn: 'Book Consultation Now',
      questionCount: 'Question {step} of 5',
      q1Title: 'How happy are you with your current smile?',
      q1Option1: '😊 Very happy - I love my smile!',
      q1Option2: '🙂 Somewhat happy - It\'s okay',
      q1Option3: '😟 Not happy - I want to improve it',
      q2Title: 'Which best describes your teeth?',
      q2Option1: 'Perfectly aligned',
      q2Option2: 'Crooked or misaligned',
      q2Option3: 'Discolored or stained',
      q2Option4: 'Chipped or damaged',
      q3Title: 'Do you have any missing teeth?',
      q3Sub: 'Slide to indicate number of missing teeth',
      q3None: '✅ No missing teeth',
      q3Few: '⚠️ {count} missing teeth - Implants recommended',
      q3Many: '🦷 {count} missing teeth - Let\'s discuss options',
      q4Title: 'How often do you brush your teeth?',
      q4Option1: '✅ Twice daily',
      q4Option2: '⚠️ Once daily',
      q4Option3: '❌ Rarely or occasionally',
      q5Title: 'Any specific dental concerns?',
      q5Placeholder: 'E.g., I have sensitive teeth, bad breath, or past dental trauma...',
      backBtn: 'Back',
      nextBtn: 'Next',
      processBtn: 'Processing...',
      getRecBtn: 'Get Recommendation'
    },
    booking: {
      title: 'Book Your Consultation',
      subtitle: 'Zero-cost initial consultation with our expert dentists',
      confirmed: 'Appointment Confirmed!',
      confirmedSub: 'We\'ve received your booking request. Our team will confirm your appointment within 2 hours via phone/email.',
      emailLabel: 'Email:',
      emailSent: 'Confirmation email sent.',
      emailNotSent: 'Not sent ({reason}).',
      viewPreview: 'View email preview',
      nameLabel: 'Name:',
      dateLabel: 'Date:',
      timeLabel: 'Time:',
      serviceLabel: 'Service:',
      whatsappBtn: 'Confirm on WhatsApp',
      bookAnother: 'Book Another Appointment',
      fullName: 'Full Name *',
      phone: 'Phone Number *',
      email: 'Email Address',
      selectAppointment: 'Select Your Appointment',
      servicePlaceholder: 'Service *',
      datePlaceholder: 'Date *',
      timeSlot: 'Time Slot *',
      goalsLabel: 'Tell us about your dental goals',
      goalsPlaceholder: 'E.g., I want to straighten my teeth, improve my smile, replace missing teeth, etc.',
      confirmBtn: 'Confirm Appointment',
      processing: 'Processing...',
      benefits: '✓ Free consultation • ✓ Personalized treatment plan • ✓ No obligations',
      services: {
        smileDesigning: 'Digital Smile Designing',
        aligners: 'Aligners & Braces',
        implants: 'Dental Implants',
        consultation: 'General Consultation'
      }
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to common questions about our treatments and services',
      searchPlaceholder: 'Search questions...',
      loading: 'Loading FAQs...',
      noResults: 'No results found',
      tryDifferent: 'Try searching with different keywords',
      helpful: 'Helpful',
      notHelpful: 'Not helpful',
      stillQuestions: 'Still have questions?',
      stillSub: 'Our expert team is ready to help. Schedule a free consultation or chat with our AI assistant.',
      btnConsult: 'Schedule Consultation',
      btnChat: 'Chat with AI',
      catGeneral: '❓ General',
      catSmile: '✨ Smile Designing',
      catAligners: '🔮 Aligners',
      catImplants: '🦷 Implants',
      q1: 'How long do treatments take?',
      a1: 'Treatment duration varies by procedure. Smile designing: 1-2 weeks. Aligners: 6-18 months. Implants: 3-6 months. Schedule a consultation for personalized timelines.',
      q2: 'Are dental implants safe?',
      a2: 'Yes, implants are FDA-approved and have a 95%+ success rate. They\'re made from biocompatible titanium and are designed to last a lifetime with proper care.',
      q3: 'Can I eat with aligners?',
      a3: 'You should remove aligners before eating or drinking anything except water. This prevents staining and damage. Wear them 22 hours daily for best results.',
      q4: 'What is the cost of treatments?',
      a4: 'Costs vary based on complexity. We offer flexible financing options. Schedule a free consultation to get a personalized quote for your specific needs.',
      q5: 'Is smile designing permanent?',
      a5: 'Smile designs using veneers typically last 10-15 years. Bonding lasts 5-7 years. Regular maintenance and good oral hygiene extend longevity.',
      q6: 'Do you accept insurance?',
      a6: 'Yes, we accept most dental insurance plans. Contact our team for details about your specific coverage and any pre-authorization requirements.',
      q7: 'How long do dental implants last?',
      a7: 'With proper care, implants can last many years or even a lifetime.',
      q8: 'Is the procedure painful?',
      a8: 'The procedure is done under anesthesia and is generally comfortable.',
      q9: 'How long does treatment take?',
      a9: 'Most implant treatments are completed within 3–7 days depending on the case.',
      q10: 'Can I travel for treatment?',
      a10: 'Yes, we provide structured plans for outstation and international patients.'
    }
  },
  es: {
    nav: {
      home: 'Inicio',
      services: 'Servicios',
      smileDesigning: 'Diseño de Sonrisa',
      alignersBraces: 'Alineadores y Frenos',
      dentalImplants: 'Implantes Dentales',
      aiPreview: 'Vista Previa IA',
      results: 'Resultados',
      assessment: 'Evaluación',
      faq: 'Preguntas Frecuentes',
      contact: 'Contacto',
      signIn: 'Iniciar Sesión',
      register: 'Registrarse',
      bookAppointment: 'Reservar Cita',
      bookNow: 'Reservar Ahora',
      logout: 'Cerrar Sesión',
      welcome: 'Bienvenido'
    },
    home: {
      heroTitle: 'Donde Se Crean Sonrisas Perfectas',
      heroSubtitle: 'Odontología avanzada para pacientes de todo el mundo. Tecnología de precisión, experiencia acreditada y compasión genuina.',
      bookConsultation: 'Reservar Consulta Gratuita',
      viewServices: 'Ver Nuestros Servicios',
      excellence: 'Centro Internacional de Excelencia',
      smiles: 'Sonrisas',
      crafted: 'Se Crean',
      wherePerfect: 'Donde',
      happyPatients: 'Pacientes Felices',
      countries: 'Países',
      excellenceYrs: 'Excelencia',
      rating: 'Calificación',
      trust: {
        jci: 'Acreditado por JCI',
        jciD: 'Instalación',
        iso: 'ISO 9001:2015',
        isoD: 'Certificado',
        docs: '15+',
        docsD: 'Médicos Especialistas',
        patients: '40+ Países',
        patientsD: 'Pacientes Internacionales',
        emergency: 'Mismo Día',
        emergencyD: 'Atención de Emergencia'
      },
      aboutTitle: 'Sobre SmileVista',
      aboutH2: 'Más que una clínica — un centro global de sonrisas',
      aboutP: 'Fundada por especialistas capacitados internacionalmente, SmileVista combina tecnología de punta con calidez genuina. Tratamos a familias locales y viajeros internacionales con el mismo cuidado de alto nivel, desde la consulta hasta el postratamiento.',
      aboutF1Title: 'Planificación Digital 3D',
      aboutF1Desc: 'Previsualiza tu sonrisa con el flujo de trabajo de diseño digital y CBCT.',
      aboutF2Title: 'Conserje Internacional',
      aboutF2Desc: 'Viaje, hotel, recogida en el aeropuerto — coordinado de extremo a extremo.',
      aboutF3Title: 'Postratamiento de Por Vida',
      aboutF3Desc: 'Controles remotos y soporte después de que regreses a casa.',
      aboutF4Title: 'Atención Amigable para la Ansiedad',
      aboutF4Desc: 'Enfoque amable con opciones modernas de confort.',
      scheduleVisit: 'Programar una Visita',
      takeQuiz: 'Hacer el Quiz de Sonrisa',
      signatureTreatments: 'Tratamientos Exclusivos',
      perfectSmile: 'Sonrisa Perfecta',
      discoverMore: 'Descubrir Más',
      service1Desc: 'Planificación digital para la perfección anatómica y la armonía facial.',
      service2Desc: 'Soluciones de ortodoncia discretas para una vida de confianza.',
      service3Desc: 'Restauraciones biocompatibles que se sienten y funcionan como dientes naturales.',
      doctors: {
        title: 'Conoce al Equipo',
        subtitle: 'Especialistas {specialists} a nivel mundial',
        specialists: 'capacitados',
        desc: 'Nuestros médicos poseen becas avanzadas y ofrecen resultados con un equilibrio entre precisión clínica y arte estético.',
        trained: 'Capacitados internacionalmente',
        founder: 'Fundador y Cirujano Dentista Jefe',
        oralMax: 'Oral y Maxilofacial',
        leadCosmetic: 'Dentista Estético y Cosmético Principal',
        cosmeticAesthetic: 'Cosmético y Estético',
        seniorImplant: 'Implantólogo Senior',
        implantology: 'Implantología'
      },
      tourism: {
        title: 'Turismo Médico',
        subtitle: 'Tu viaje hacia una sonrisa {better}',
        better: 'mejor',
        desc: 'Ahorra un 40–70% en odontología de clase mundial. Nuestro equipo te ayuda con orientación de viaje, hoteles asociados y postratamiento para que puedas concentrarte en tu tratamiento.',
        step1Title: 'Consulta virtual gratuita',
        step1Desc: 'Comparte radiografías/fotos. Recibe un plan y presupuesto en 24 horas.',
        step2Title: 'Viaje y alojamiento',
        step2Desc: 'Recogida en el aeropuerto + hoteles asociados a minutos de la clínica.',
        step3Title: 'Tratamiento en SmileVista',
        step3Desc: 'La mayoría de los paquetes de procedimientos múltiples se completan en 5–10 días.',
        step4Title: 'Postratamiento remoto de por vida',
        step4Desc: 'Registros digitales y seguimientos después de que regreses a casa.',
        btn: 'Planear mi viaje dental',
        whyTitle: '¿Por qué la India para la odontología?',
        whyDesc: 'Resultados de clase mundial a una fracción del costo — con médicos capacitados en instituciones globales líderes.',
        feat1Title: 'Vuelos directos',
        feat1Desc: 'Desde Emiratos Árabes Unidos, Reino Unido, EE. UU., Australia y más',
        feat2Title: 'Hoteles asociados',
        feat2Desc: '4★ y 5★ con tarifas exclusivas',
        feat3Title: 'Equipo de especialistas',
        feat3Desc: 'Estética, implantes, alineadores',
        feat4Title: 'Soporte de visa',
        feat4Desc: 'Documentos + carta médica',
        savings: 'Ahorro medio de costos',
        vsCare: 'vs. atención equivalente en Reino Unido, EE. UU. o Australia'
      },
      testimonials: {
        title: 'Historias de pacientes',
        subtitle: 'Sonrisas compartidas en {across}',
        across: 'todo el mundo',
        desc: 'Pacientes reales, resultados reales — desde Londres hasta Lagos, Sídney hasta São Paulo. Cada sonrisa cuenta una historia de confianza.',
        t1: '“Volé desde Dubái para una reconstrucción completa de la boca. Desde la primera consulta por WhatsApp hasta el ajuste final, todo fue perfecto. Valió la pena cada hora de viaje.”',
        t2: '“Tenía pavor a los dentistas, pero aquí me sentí completamente a gusto. Calidad y valor excepcionales en comparación con los precios del Reino Unido.”',
        t3: '“Mis carillas son perfectas. Consulté en tres países — la calidad aquí superó a todos ellos a un tercio del precio.”'
      },
      contact: {
        title: 'Ponte en contacto',
        subtitle: 'Reserva tu consulta {free}',
        free: 'gratuita',
        desc: 'Ya sea local o internacional, nuestro equipo crea tu plan personalizado. Las primeras consultas son gratuitas e incluyen una evaluación digital completa.',
        phone: 'Lun–Sáb, 9 AM – 8 PM IST',
        email: 'Respuesta en 2 horas',
        location: 'A 15 minutos del centro de la ciudad',
        locName: 'Koramangala, Bengaluru, India',
        formTitle: 'Solicitar una cita',
        formSub: 'Completa este formulario rápido y nos pondremos en contacto para programar tu consulta gratuita.',
        firstName: 'Nombre',
        lastName: 'Apellido',
        emailLabel: 'Correo electrónico',
        messageLabel: 'Mensaje',
        messagePlaceholder: 'Cuéntanos qué quieres mejorar...',
        btnSend: 'Enviar Mensaje',
        btnSending: 'Enviando...',
        sentTitle: '¡Mensaje Enviado!',
        sentSub: 'Gracias por contactarnos. Nos pondremos en contacto contigo en breve.',
        btnWhatsapp: 'Seguimiento por WhatsApp',
        btnAnother: 'Enviar otro mensaje',
        btnBooking: 'Ir a la página de reserva completa'
      }
    },
    services: {
      whyChoose: '¿Por Qué Elegir Este Tratamiento?',
      journeyTitle: 'Tu Camino Hacia una Sonrisa Perfecta',
      journeySub: 'Un enfoque clínico paso a paso',
      theResult: 'El Resultado',
      resultSub: 'Una obra maestra de precisión estética y excelencia clínica',
      beforeTreatment: 'Antes del Tratamiento',
      afterReveal: 'Después de la Transformación',
      transformation: 'Transformación del Paciente',
      quote: '"Mi confianza nunca ha sido mayor. La precisión es de clase mundial."',
      readyTitle: '¿Listo para Transformar Tu Sonrisa?',
      readySub: 'Programa tu consulta sin costo hoy y obtén un plan de tratamiento 3D personalizado.',
      bookNowBtn: 'Reservar Cita Ahora',
      viewResultsBtn: 'Ver Más Resultados'
    },
    smileDesigning: {
      title: "Diseño Digital de Sonrisa",
      subtitle: "Cambios de imagen de sonrisa diseñados con precisión y adaptados a tus rasgos faciales y personalidad.",
      benefit1Title: "Armonía Estética",
      benefit1Desc: "Alineamos tus dientes según la 'Proporción Áurea' para una simetría facial perfecta.",
      benefit2Title: "Visualización 3D",
      benefit2Desc: "Mira tu futura sonrisa en pantalla antes de que toquemos tus dientes.",
      benefit3Title: "Procedimiento en un Solo Día",
      benefit3Desc: "Muchos de nuestros casos de diseño de sonrisa se completan en solo una o dos sesiones.",
      step1Title: "Escaneo Digital",
      step1Desc: "Tomamos impresiones digitales de alta resolución con nuestro escáner intraoral.",
      step2Title: "Mapeo Artístico",
      step2Desc: "Nuestros especialistas diseñan la curva de tu sonrisa con software dental profesional.",
      step3Title: "Diseño de Prueba",
      step3Desc: "Pruebas un modelo temporal para asegurar que te guste el aspecto y la sensación.",
      step4Title: "Revelación Final",
      step4Desc: "Se aplican carillas E-max premium o resinas para tu look final."
    },
    alignersBraces: {
      title: "Alineadores y Frenos",
      subtitle: "El camino moderno hacia una sonrisa más recta y saludable, de forma discreta y cómoda.",
      benefit1Title: "Comodidad Invisible",
      benefit1Desc: "Los alineadores transparentes son prácticamente imperceptibles y se pueden quitar para comer y limpiar.",
      benefit2Title: "Movimiento de Precisión",
      benefit2Desc: "La planificación del tratamiento 3D asegura que cada diente se mueva exactamente donde debe estar.",
      benefit3Title: "Encías Más Saludables",
      benefit3Desc: "Los dientes rectos son más fáciles de limpiar, lo que conduce a una mejor salud bucal a largo plazo.",
      step1Title: "Consulta",
      step1Desc: "Evaluamos tu mordida y discutimos tus objetivos de alineación.",
      step2Title: "Planificación Digital",
      step2Desc: "Un modelo digital 3D muestra tu transformación de principio a fin.",
      step3Title: "Cubetas Personalizadas",
      step3Desc: "Recibes una serie de alineadores personalizados para usar durante todo tu tratamiento.",
      step4Title: "Retención",
      step4Desc: "Proporcionamos retenedores para mantener tu sonrisa perfectamente alineada por años."
    },
    dentalImplants: {
      title: "Implantes Dentales",
      subtitle: "Restauraciones biocompatibles que se sienten, se ven y funcionan exactamente como los dientes naturales.",
      benefit1Title: "Sensación Natural",
      benefit1Desc: "Los implantes se fusionan con el hueso de la mandíbula, proporcionando estabilidad y comodidad inigualables.",
      benefit2Title: "Salud Ósea",
      benefit2Desc: "Previene la pérdida de hueso de la mandíbula que suele seguir a la pérdida de dientes, preservando la estructura facial.",
      benefit3Title: "Solución de Por Vida",
      benefit3Desc: "Con el cuidado adecuado, los implantes dentales están diseñados para durar toda la vida.",
      step1Title: "Preparación del Sitio",
      step1Desc: "Aseguramos que la base esté saludable y lista para el implante.",
      step2Title: "Colocación",
      step2Desc: "El poste de titanio se coloca con precisión en el hueso de la mandíbula.",
      step3Title: "Curación",
      step3Desc: "Un período de oseointegración permite que el implante se adhiera al hueso.",
      step4Title: "Restauración",
      step4Desc: "Se coloca una corona personalizada, completando tu sonrisa funcional y estética."
    },
    aiPreview: {
      title: 'Vista Previa de Sonrisa IA',
      subtitle: 'Sube una foto y mira tu futura sonrisa en segundos usando nuestra avanzada tecnología de IA.',
      uploadTitle: 'Sube Tu Foto',
      uploadSub: 'Asegúrate de que tus dientes sean visibles para mejores resultados',
      btnUpload: 'Elegir Foto',
      btnProcess: 'Generar Vista Previa',
      disclaimer: '*Esta es una simulación generada por IA solo para fines de visualización.'
    },
    results: {
      title: 'Casos de Éxito',
      subtitle: 'Transformaciones reales de nuestros pacientes globales. Sé testigo del poder de la odontología de precisión.',
      filterAll: 'Todos los Casos',
      filterSmile: 'Diseño de Sonrisa',
      filterAligners: 'Alineadores',
      filterImplants: 'Implantes'
    },
    assessment: {
      title: 'Evaluación de Sonrisa',
      quizTitle: 'Cuestionario de Evaluación',
      subtitle: 'Responde algunas preguntas para obtener recomendaciones personalizadas',
      resultTitle: 'Tu Plan de Tratamiento',
      resultSub: 'Basado en tus respuestas, esto es lo que recomendamos',
      recTitle: 'Tratamiento Recomendado',
      estCost: 'Costo Estimado',
      duration: 'Duración del Tratamiento',
      successRate: 'Tasa de Éxito',
      nextSteps: '¿Qué sigue ahora?',
      step1: 'Programa tu consulta gratuita',
      step2: 'Imágenes digitales 3D avanzadas',
      step3: 'Plan de tratamiento y precios detallados',
      step4: 'Opciones de pago flexibles disponibles',
      retakeBtn: 'Repetir Cuestionario',
      bookConsultBtn: 'Reservar Consulta Ahora',
      questionCount: 'Pregunta {step} de 5',
      q1Title: '¿Qué tan feliz eres con tu sonrisa actual?',
      q1Option1: '😊 Muy feliz - ¡Amo mi sonrisa!',
      q1Option2: '🙂 Algo feliz - Está bien',
      q1Option3: '😟 No soy feliz - Quiero mejorarla',
      q2Title: '¿Qué describe mejor tus dientes?',
      q2Option1: 'Perfectamente alineados',
      q2Option2: 'Torcidos o desalineados',
      q2Option3: 'Decolorados o manchados',
      q2Option4: 'Astillados o dañados',
      q3Title: '¿Te falta algún diente?',
      q3Sub: 'Desliza para indicar el número de dientes faltantes',
      q3None: '✅ No me faltan dientes',
      q3Few: '⚠️ {count} dientes faltantes - Implantes recomendados',
      q3Many: '🦷 {count} dientes faltantes - Hablemos de las opciones',
      q4Title: '¿Con qué frecuencia te cepillas los dientes?',
      q4Option1: '✅ Dos veces al día',
      q4Option2: '⚠️ Una vez al día',
      q4Option3: '❌ Rara vez u ocasionalmente',
      q5Title: '¿Alguna preocupación dental específica?',
      q5Placeholder: 'Ej: tengo dientes sensibles, mal aliento o trauma dental previo...',
      backBtn: 'Atrás',
      nextBtn: 'Siguiente',
      processBtn: 'Procesando...',
      getRecBtn: 'Obtener Recomendación'
    },
    booking: {
      title: 'Reserva Tu Consulta',
      subtitle: 'Consulta inicial sin costo con nuestros dentistas expertos',
      confirmed: '¡Cita Confirmada!',
      confirmedSub: 'Hemos recibido su solicitud de reserva. Nuestro equipo confirmará su cita en un plazo de 2 horas por teléfono/correo electrónico.',
      emailLabel: 'Correo electrónico:',
      emailSent: 'Correo electrónico de confirmación enviado.',
      emailNotSent: 'No enviado ({reason}).',
      viewPreview: 'Ver vista previa del correo',
      nameLabel: 'Nombre:',
      dateLabel: 'Fecha:',
      timeLabel: 'Hora:',
      serviceLabel: 'Servicio:',
      whatsappBtn: 'Confirmar por WhatsApp',
      bookAnother: 'Reservar Otra Cita',
      fullName: 'Nombre Completo *',
      phone: 'Número de Teléfono *',
      email: 'Dirección de Correo Electrónico',
      selectAppointment: 'Seleccione Su Cita',
      servicePlaceholder: 'Servicio *',
      datePlaceholder: 'Fecha *',
      timeSlot: 'Horario *',
      goalsLabel: 'Cuéntanos sobre tus objetivos dentales',
      goalsPlaceholder: 'Ej: quiero enderezar mis dientes, mejorar mi sonrisa, reemplazar dientes faltantes, etc.',
      confirmBtn: 'Confirmar Cita',
      processing: 'Procesando...',
      benefits: '✓ Consulta gratuita • ✓ Plan de tratamiento personalizado • ✓ Sin obligaciones',
      services: {
        smileDesigning: 'Diseño Digital de Sonrisa',
        aligners: 'Alineadores y Frenos',
        implants: 'Implantes Dentales',
        consultation: 'Consulta General'
      }
    },
    faq: {
      title: 'Preguntas Frecuentes',
      subtitle: 'Encuentra respuestas a preguntas comunes sobre nuestros tratamientos y servicios',
      searchPlaceholder: 'Buscar preguntas...',
      loading: 'Cargando preguntas...',
      noResults: 'No se encontraron resultados',
      tryDifferent: 'Intenta buscar con otras palabras clave',
      helpful: 'Útil',
      notHelpful: 'No es útil',
      stillQuestions: '¿Aún tienes preguntas?',
      stillSub: 'Nuestro equipo de expertos está listo para ayudar. Programa una consulta gratuita o chatea con nuestro asistente de IA.',
      btnConsult: 'Programar Consulta',
      btnChat: 'Chatear con IA',
      catGeneral: '❓ General',
      catSmile: '✨ Diseño de Sonrisa',
      catAligners: '🔮 Alineadores',
      catImplants: '🦷 Implantes',
      q1: '¿Cuánto tiempo duran los tratamientos?',
      a1: 'La duración del tratamiento varía según el procedimiento. Diseño de sonrisa: 1-2 semanas. Alineadores: 6-18 meses. Implantes: 3-6 meses. Programa una consulta para cronogramas personalizados.',
      q2: '¿Son seguros los implantes dentales?',
      a2: 'Sí, los implantes están aprobados por la FDA y tienen una tasa de éxito del 95%+. Están hechos de titanio biocompatible y están diseñados para durar toda la vida con el cuidado adecuado.',
      q3: '¿Puedo comer con los alineadores puestos?',
      a3: 'Debes quitarte los alineadores antes de comer o beber cualquier cosa que no sea agua. Esto evita manchas y daños. Úsalos 22 horas al día para obtener mejores resultados.',
      q4: '¿Cuál es el costo de los tratamientos?',
      a4: 'Los costos varían según la complejidad. Ofrecemos opciones de financiamiento flexibles. Programa una consulta gratuita para obtener un presupuesto personalizado para tus necesidades específicas.',
      q5: '¿El diseño de sonrisa es permanente?',
      a5: 'Los diseños de sonrisa con carillas suelen durar de 10 a 15 años. El adhesivo dura de 5 a 7 años. El mantenimiento regular y una buena higiene bucal prolongan su duración.',
      q6: '¿Aceptan seguros?',
      a6: 'Sí, aceptamos la mayoría de los planes de seguros dentales. Contacta a nuestro equipo para obtener detalles sobre tu cobertura específica y cualquier requisito de preautorización.'
    }
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (path) => {
    const keys = path.split('.');
    let value = translations[language];
    for (const key of keys) {
      value = value?.[key];
    }
    return value || path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export default translations;
