import fs from 'fs';
import path from 'path';
import readline from 'readline';

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(prompt) {
  return new Promise((resolve) => rl.question(prompt, (ans) => resolve(ans)));
}

function escapeEnvValue(v) {
  const value = String(v ?? '').trim();
  if (!value) return '';
  // Quote if it contains spaces or special chars
  if (/[\s"'`\\]/.test(value)) return JSON.stringify(value);
  return value;
}

function mask(value) {
  const v = String(value || '');
  if (v.length <= 4) return '*'.repeat(v.length);
  return `${v.slice(0, 2)}${'*'.repeat(Math.max(4, v.length - 4))}${v.slice(-2)}`;
}

async function main() {
  const repoRoot = process.cwd();
  const envPath = path.join(repoRoot, '.env');

  console.log('\nSmileVista Email Setup (.env)\n');
  console.log('This will create/update a local `.env` file (ignored by git).');
  console.log('Tip: For Gmail, use an App Password (not your normal password).\n');

  const smtpUser = (await ask('Gmail address (SMTP_USER): ')).trim();
  const smtpPass = (await ask('Gmail App Password (SMTP_PASS): ')).trim();
  const fromName = (await ask('From name (default: SmileVista Dental): ')).trim() || 'SmileVista Dental';

  if (!smtpUser || !smtpPass) {
    console.log('\nMissing SMTP_USER or SMTP_PASS. Aborting.\n');
    rl.close();
    process.exitCode = 1;
    return;
  }

  const lines = [
    '## Auto-generated by `npm run setup:email`',
    'SMTP_SERVICE=gmail',
    `SMTP_USER=${escapeEnvValue(smtpUser)}`,
    `SMTP_PASS=${escapeEnvValue(smtpPass)}`,
    `SMTP_FROM=${escapeEnvValue(`${fromName} <${smtpUser}>`)}`,
    ''
  ];

  fs.writeFileSync(envPath, lines.join('\n'), 'utf8');

  console.log('\nSaved `.env` with:');
  console.log(`- SMTP_USER: ${smtpUser}`);
  console.log(`- SMTP_PASS: ${mask(smtpPass)}`);
  console.log(`- SMTP_FROM: ${fromName} <${smtpUser}>`);
  console.log('\nNow restart the backend: `npm run server`\n');

  rl.close();
}

main().catch((err) => {
  console.error('Setup failed:', err);
  rl.close();
  process.exitCode = 1;
});

